# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-23 02:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('beds', '0001_initial'), ('beds', '0002_auto_20170518_0247'), ('beds', '0003_auto_20170518_0249'), ('beds', '0004_auto_20170519_2207'), ('beds', '0005_auto_20170520_1102'), ('beds', '0006_auto_20170520_1641'), ('beds', '0007_alertrule')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('log', models.TextField(default='{}')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beds.Bed')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, default='', max_length=255)),
                ('style', models.CharField(blank=True, default='label label-info', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='bed',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='beds.Status'),
        ),
        migrations.AddField(
            model_name='bed',
            name='tags',
            field=models.ManyToManyField(blank=True, to='beds.Tag'),
        ),
        migrations.AddField(
            model_name='bed',
            name='name',
            field=models.CharField(default='Bed', max_length=255),
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
        migrations.AddField(
            model_name='bed',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bed',
            name='room',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='status',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='status',
            name='style',
            field=models.CharField(blank=True, default='label label-info', max_length=255),
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_rule', models.TextField(default='{}')),
            ],
        ),
    ]
