# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-20 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beds', '0005_auto_20170520_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='status',
            name='style',
            field=models.CharField(blank=True, default='label label-info', max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='style',
            field=models.CharField(blank=True, default='label label-info', max_length=255),
        ),
    ]
